config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

class AdminConstraint
  def matches?(request)
    return false unless request.session[:current_admin_id].present?
    admin = Administrator.find_by(id: request.session[:current_admin_id])
    admin.present?
  end
end

Rails.application.routes.draw do

  get 'home/index'
  namespace :admin do
    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout
    resource :account, only: [:edit, :update]

    root to: 'dashboard#index'
  end

  # write your routes here

  get '/signup', to: 'users#new'
  resources :users


  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new
  #mount ActionCable.server => '/cable'
  root to: 'home#index'
end

app/models/administrator.rb
# frozen_string_literal: true

class Administrator < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { email.downcase! }
  
    validates :name, presence: true, length: { maximum: 50 }
  
    validates :email, presence: true, length: { maximum: 255 }
    #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    VALID_EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
    validates :email, format: { with: VALID_EMAIL_REGEX, on: :create },
                      uniqueness: true
  
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
  end
  

app/controllers/admin/accounts_controller.rb
# frozen_string_literal: true

class Admin::AccountsController < Admin::BaseController
  def edit
  end

  def update
    if current_admin.authenticate(params.require(:administrator)[:current_password])
      if current_admin.update(admin_params)
        admin_sign_out
        redirect_to admin_login_path, notice: "Account has been updated, please log in again"
      else
        render "edit"
      end
    else
      flash.now[:alert] = "Old password is wrong, try again"
      render "edit"
    end
  end

  private
    def admin_params
      params.require(:administrator).permit(:name, :password, :password_confirmation)
    end
end

app/controllers/admin/base_controller.rb
# frozen_string_literal: true

class Admin::BaseController < ActionController::Base
  layout "admin"

  protect_from_forgery with: :exception

  before_action :authenticate_admin!

  helper_method :current_admin

  private
    def authenticate_admin!
      if current_admin.blank?
        redirect_to admin_login_path
        return
      end

      if current_admin.password_digest != session[:current_admin_token]
        redirect_to admin_login_path, alert: "Password was changed, please log in again"
        nil
      end
    end

    def current_admin
      @_current_admin ||= session[:current_admin_id] && Administrator.find_by(id: session[:current_admin_id])
    end

    def admin_sign_in(admin)
      session[:current_admin_id] = admin.id
      session[:current_admin_token] = admin.password_digest
    end

    def admin_sign_out
      session[:current_admin_id] = nil
      session[:current_admin_token] = nil
      @_current_admin = nil
    end
end

app/controllers/admin/dashboard_controller.rb
# frozen_string_literal: true

class Admin::DashboardController < Admin::BaseController
  def index
    @admin_count = Administrator.all.size
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Admin::BaseController
  skip_before_action :authenticate_admin!, only: [:new, :create]

  before_action do
    @full_render = true
  end

  def new
  end

  def create
    admin = Administrator.find_by(name: params[:name])
    if admin && admin.authenticate(params[:password])
      admin_sign_in(admin)
      redirect_to admin_root_path
    else
      flash.now[:alert] = "Username or password is wrong"
      render "new"
    end
  end

  def destroy
    admin_sign_out
    redirect_to admin_login_path
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :mail,
        :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # Generate `{controller}-{action}-page` class for body element
  def body_class
    path = controller_path.tr("/_", "-")
    action_name_map = {
      index: "index",
      new: "edit",
      edit: "edit",
      update: "edit",
      patch: "edit",
      create: "edit",
      destory: "index"
    }
    mapped_action_name = action_name_map[action_name.to_sym] || action_name
    body_class_page =
      if controller.is_a?(HighVoltage::StaticPage) && params.key?(:id) && params[:id] !~ /\A[-+]?[0-9]*\.?[0-9]+\Z/
        id_name = params[:id].tr("_", "-") + "-page"
        format("%s-%s-%s", path, action_name, id_name)
      else
        format("%s-%s-page", path, mapped_action_name)
      end

    body_class_page
  end

  # Admin active for helper
  def admin_active_for(controller_name, navbar_name)
    if controller_name.to_s == admin_root_path
      return controller_name.to_s == navbar_name.to_s ? "active" : ""
    end
    navbar_name.to_s.include?(controller_name.to_s) ? "active" : ""
  end

  def current_path
    request.env["PATH_INFO"]
  end

  def flash_class(level)
    case level
    when "notice", "success" then "alert alert-success alert-dismissible"
    when "info" then "alert alert-info alert-dismissible"
    when "warning" then "alert alert-warning alert-dismissible"
    when "alert", "error" then "alert alert-danger alert-dismissible"
    end
  end

  def full_title(page_title = "")
    base_title = "Ruby on Rails Sample App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
    # Returns the gravatar for the given user.
    def gravatar_for(user, size: 80)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/admin/accounts/edit.html.slim
- content_for :title do
  | Account Setting

.card.card-primary
  .card-header.with-border
    h3.card-title
      | Edit Account
  = simple_form_for current_admin, url: admin_account_path do |f|
    .card-body
      = f.input :name, label: 'Administrator Name'
      = f.input :current_password, label: 'Current Password', required: true
      = f.input :password, label: 'New Password( Blank if not modify )'
      = f.input :password_confirmation, label: 'Confirm New Password'
    .card-footer
      = f.submit 'Update Account', class: 'btn btn-primary'

app/views/admin/dashboard/index.html.slim
.container-fluid
  .row
    .col-lg-6
      .card.card-primary.card-outline
        .card-body
          h5.card-title Administrators: #{@admin_count}
          p.card-text

app/views/home/index.html.slim
.jumbotron.center
  h1.display-4 Hello World, welcome to the Sample App
  p.lead This is the feature branch home page for the Ruby on Rails Sample App.
  hr.my-4
  = link_to "Sign Up", signup_path, class: "btn btn-primary btn-lg"

= link_to image_tag("rails.svg", alt: "Rails logo", width: "200"), "https://rubyonrails.org"

app/views/layouts/_footer.html.slim
footer.footer
  small 
    | The
    a< href="https://rubyonrails.org" Ruby on Rails Org
  nav
    ul.nav
      li.nav-item= link_to "About", page_url("about"), class: "nav-link"
      li.nav-item= link_to "Contact", page_url("contact"), class: "nav-link"
      li.nav-item
        a.nav-link href="https://news.railstutorial.org" News

app/views/layouts/_header.html.slim
header
    nav.navbar.navbar-expand-lg.navbar-light.bg-light
        = link_to "Sample App", root_path, id: "logo", class: "navbar-brand"
        ul.navbar-nav.ml-auto
            li.nav-item= link_to link_to "Home", root_path, class: "navbar-brand"
            li.nav-item= link_to link_to "Help", page_url("help"), class: "navbar-brand"
            li.nav-item= link_to link_to "Log In", "#", class: "navbar-brand"

app/views/layouts/_meta.html.slim
meta charset='utf-8'
meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"
meta name="renderer" content="webkit"
meta http-equiv="cleartype" content="on"
meta name="HandheldFriendly" content="True"
meta name="MobileOptimized" content="320"
meta name="turbolinks-cache-control" content="no-cache"

app/views/layouts/_pack_tags.html.slim
= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'ga', 'data-turbolinks-track': 'reload'

app/views/layouts/_shim.html.slim
= csrf_meta_tags
= action_cable_meta_tag

app/views/layouts/admin.html.slim
doctype html
html
  head
    meta charset='utf-8'
    meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
    meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"
    meta name="renderer" content="webkit"
    meta http-equiv="cleartype" content="on"
    meta name="HandheldFriendly" content="True"
    meta name="MobileOptimized" content="320"
    meta name="turbolinks-cache-control" content="no-cache"
    - if content_for?(:title)
      title = format("%s - Dashboard", yield(:title))
    - else
      title template_app Dashboard
    = csrf_meta_tags
    = action_cable_meta_tag
    = content_for?(:head) ? yield(:head) : ''
    = stylesheet_pack_tag 'admin', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'admin', 'data-turbolinks-track': 'reload'
    = favicon_link_tag asset_pack_path("media/images/favicon.ico")
  body.hold-transition.skin-blue.sidebar-mini.layout-fixed.admin-page class=body_class
    - if @full_render
      = yield
    - else
      main.wrapper
        = render 'shared/admin/header'
        = render 'shared/admin/sidebar'
        .content-wrapper
          section.content-messages
            = render 'shared/admin/flash_messages'
          section.content-header
          section.content
            = yield
        aside.control-sidebar.control-sidebar-dark
          /! Control sidebar content goes here
          .p-3
            h5 Title
            p Sidebar content
        /! /.control-sidebar
        /! Main Footer
        footer.main-footer
          /! To the right
          .float-right.d-none.d-sm-inline
            | Anything you want
          /! Default to the left
          strong
            | Copyright &copy; 2019 - All rights reserved.
          | Theme by AdminLTE.io

app/views/layouts/application.html.slim
doctype html
html
  head
    = render "layouts/meta"
    title = full_title(yield(:title))
    = render "layouts/shim"
    = content_for?(:head) ? yield(:head) : ''
    = render "layouts/pack_tags"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = favicon_link_tag asset_pack_path("media/images/favicon.ico")
  body class=body_class
    = render "layouts/header"
    main
      .container
        - flash.each do |message_type, message|
          div class="aler alert-#{message_type}" = message
        == yield
        = render "layouts/footer"
        = debug(params) if Rails.env.development?

app/views/pages/about.html.slim
- content_for :title do
  | About

.container.text-center
  p
  h1 About Page
  hr
  p This is an example for about page, using `high_voltage`
  br
  br
  br
  = link_to 'Back to Home', root_path

app/views/pages/contact.html.slim
- content_for :title do
  | Contact

.container.text-center
  p
  h1 Contact Page
  hr
  p This is an example for contact page, using `high_voltage`
  br
  br
  br
  = link_to 'Back to Home', root_path

app/views/pages/help.html.slim
- content_for :title do
  | Help

.container.text-center
  p
  h1 Help
  hr
  p Get help on
  a< href="https://guides.rubyonrails.org/" Ruby on Rails
  br
  br
  br
  = link_to 'Back to Home', root_path

app/views/shared/_error_messages.html.slim
- if @user.errors.any?
  #error_explanation
    .alert.alert-danger
      | The form contains
      =< pluralize(@user.errors.count, "error")
    ul
      - @user.errors.full_messages.each do |msg|
        li = msg

app/views/shared/admin/_flash_messages.html.slim
- flash.each do |key, value|
  = content_tag :div, class: flash_class(key) do
    button.close[type="button" data-dismiss="alert"]
      | ×
    = value

app/views/shared/admin/_header.html.slim
nav.main-header.navbar.navbar-expand.navbar-white.navbar-light.border-bottom
  /! Left navbar links
  ul.navbar-nav
    li.nav-item
      a.nav-link data-widget="pushmenu" href="javascript:void(0)"
        i.fas.fa-bars
  /! SEARCH FORM
  - if content_for?(:search)
    = yield(:search)
  /! Right navbar links
  ul.navbar-nav.ml-auto
    /! Messages Dropdown Menu
    li.nav-item.dropdown.show
      a.nav-link.dropdown-toggle href="javascript:void(0)" data-toggle="dropdown"
        span
          = current_admin.name
      ul.dropdown-menu.dropdown-menu-right
        li.user-header
          = link_to 'Account Setting', edit_admin_account_path, class: 'dropdown-item'
          .dropdown-divider
          = link_to 'Logout', admin_logout_path, method: :delete, class: 'dropdown-item'

app/views/shared/admin/_sidebar.html.slim
/! Main Sidebar Container
aside.main-sidebar.sidebar-dark-primary.elevation-4
  /! Brand Logo
  a.brand-link href=admin_root_path
    = image_pack_tag 'logo.png', class: 'brand-image img-circle elevation-3'
    span.brand-text.font-weight-light Dashboard
  /! Sidebar
  .sidebar
    /! Sidebar Menu
    nav.mt-2
      ul.nav.nav-pills.nav-sidebar.flex-column data-accordion="false" data-widget="treeview" role="menu"
        li.nav-item
          = link_to admin_root_path, class: "nav-link #{admin_active_for(admin_root_path, current_path)}" do
            i.nav-icon.fas.fa-tachometer-alt
            span Dashboard
        li.nav-item
          = link_to '#', class: "nav-link" do
            i.nav-icon.fas.fa-th
            span Your menu

app/views/users/new.html.slim
- content_for :title do
  | Sign up

.row
  .col-md-6.offset-md-3
    = form_with(model: @user, local: true) do |f|
      = render "shared/error_messages"

      = f.label :name
      = f.text_field :name, class: "form-control"

      = f.label :name, "Another name label"

      = f.label :email
      = f.text_field :email, class: "form-control"

      = f.label :password
      = f.password_field :password, class: "form-control"

      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation, class: "form-control"

      = f.submit "Create my account", class: "btn btn-primary"

app/views/users/show.html.slim
- content_for :title do
  = @user.name

.row
  aside.col-md-4
    section.user-info
      h1 
        = gravatar_for @user
        =< @user.name
        